### ISSUE TITLE
希望，新增匹配位置，而不是全局搜索。

### ISSUE THREAD

**Issue by 1021683053** [aui/pinyin-engine#1]
希望，新增匹配位置，而不是全局搜索。

**Comment by aui** [comment]
没明白你说的意思，能否详细描述下？

**Comment by 1021683053** [comment]
当前是全文搜索，
例子：
String:'中山大学'
key: 'daxue'
情况1(当前版本): 可以搜索到，因为是全文匹配 /reg/g
情况2(未实现): /^reg/ 匹配开始。

**Comment by 1021683053** [comment]
还有个问题就是无法匹配大写英文：
![image](https://user-images.githubusercontent.com/7711802/30156138-6a788b50-93f1-11e7-8c17-9542a3d1cf30.png)

![image](https://user-images.githubusercontent.com/7711802/30156149-7490dc00-93f1-11e7-94ca-f8f00d84487f.png)

![image](https://user-images.githubusercontent.com/7711802/30156156-7aab81b2-93f1-11e7-8985-57c5b1f3aa2b.png)
