### ISSUE TITLE
匹配大写开头的英文，匹配不到

### ISSUE THREAD

**Issue by fantasychen666** [aui/pinyin-engine#6]
比如 [{name:'Alice'}] 这种，如果输入'a'，匹配时会过滤掉。
我在自己本地改的，src/engine.js的第59行，

建议：
原来的  indexs[index].indexOf(keyword) 改为 indexs[index].toLowerCase().indexOf(keyword) 
就可以了。

**Comment by mask2012** [comment]
牛！ 我用这个办法搞定了
详细步骤：
1. 找到node_module里的pinyin-engine/src/engine.js 第59行，加一个tolowercase
2. npm install一下
3. package.json里加上script  ‘webpack’
  "scripts": {
    "test": "mocha",
    "webpack": "webpack"
  },
4. npm run webpack  就会打包到dist目录里，这时再测试就成功了。

如果是团队项目一定要记得把dist里的文件给每个团队成员覆盖，不然别人一打包bug又出现了。

**Comment by mask2012** [comment]
我其实看到2017年就已经修复这个bug了，而且demo里也是没有这个bug的，后来仔细对比，发现github上的代码和npm包的同为1.1.0版本，但是代码内容却不一样，我感觉是修复的代码并没有提交到npm上，才导致这些问题

**Comment by aui** [comment]
最新版本已经发布解决了此问题
