### ISSUE TITLE
不支持英文大写搜索

### ISSUE THREAD

**Issue by Mathround** [aui/pinyin-engine#8]
比如数据里有ABC这字符串，直接搜是找不到的

**Comment by tyzr001** [comment]
是的，我在使用的时候发现GPRS匹配不上

**Comment by mask2012** [comment]
是的，也发现这个bug了
感觉原因是输入的keyword会自动转成小写去匹配汉字的小写拼音
但是不曾想，如果待匹配列表里，除了汉字还可能夹杂大小写字母，结果大写字母就不可能被匹配上了。

**Comment by mask2012** [comment]
发现通过 #6 可以自己临时解决这个bug，我写了详细步骤
彻底的修复等待作者更新吧。。

**Comment by aui** [comment]
已经发布版本解决了此问题
